# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import skew
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("D:\\Ameng\\Data Science Project\\breast-cancer-prediciton\\data\\processed\\removed_multicollinearity.csv")

In [3]:
df.head()

,id,diagnosis,texture_mean,smoothness_mean,compactness_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,texture_se,area_se,...,symmetry_se,fractal_dimension_se,texture_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,10.38,0.11840,0.27760,0.14710,0.2419,0.07871,0.9053,153.40,...,0.03003,0.006193,17.33,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,17.77,0.08474,0.07864,0.07017,0.1812,0.05667,0.7339,74.08,...,0.01389,0.003532,23.41,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,21.25,0.10960,0.15990,0.12790,0.2069,0.05999,0.7869,94.03,...,0.02250,0.004571,25.53,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,20.38,0.14250,0.28390,0.10520,0.2597,0.09744,1.1560,27.23,...,0.05963,0.009208,26.50,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,14.34,0.10030,0.13280,0.10430,0.1809,0.05883,0.7813,94.44,...,0.01756,0.005115,16.67,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    int64
 2   texture_mean             569 non-null    float64
 3   smoothness_mean          569 non-null    float64
 4   compactness_mean         569 non-null    float64
 5   concave points_mean      569 non-null    float64
 6   symmetry_mean            569 non-null    float64
 7   fractal_dimension_mean   569 non-null    float64
 8   texture_se               569 non-null    float64
 9   area_se                  569 non-null    float64
 10  smoothness_se            569 non-null    float64
 11  compactness_se           569 non-null    float64
 12  concavity_se             569 non-null    float64
 13  concave points_se        569 non-null    float64
 14  symmetry_se              569 non-null    float64
 15  fractal_dimension_se     569 non-null    float64
 16  texture_worst            569 non-null    float64
 17  area_worst               569 non-null    float64
 18  smoothness_worst         569 non-null    float64
 19  compactness_worst        569 non-null    float64
 20  concavity_worst          569 non-null    float64
 21  concave points_worst     569 non-null    float64
 22  symmetry_worst           569 non-null    float64
 23  fractal_dimension_worst  569 non-null    float64
dtypes: float64(22), int64(2)
memory usage: 106.8 KB

In [5]:
df.describe()

,id,diagnosis,texture_mean,smoothness_mean,compactness_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,texture_se,area_se,...,symmetry_se,fractal_dimension_se,texture_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,0.372583,19.289649,0.096360,0.104341,0.048919,0.181162,0.062798,1.216853,40.337079,...,0.020542,0.003795,25.677223,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,1.250206e+08,0.483918,4.301036,0.014064,0.052813,0.038803,0.027414,0.007060,0.551648,45.491006,...,0.008266,0.002646,6.146258,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,8.670000e+03,0.000000,9.710000,0.052630,0.019380,0.000000,0.106000,0.049960,0.360200,6.802000,...,0.007882,0.000895,12.020000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.692180e+05,0.000000,16.170000,0.086370,0.064920,0.020310,0.161900,0.057700,0.833900,17.850000,...,0.015160,0.002248,21.080000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,9.060240e+05,0.000000,18.840000,0.095870,0.092630,0.033500,0.179200,0.061540,1.108000,24.530000,...,0.018730,0.003187,25.410000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,8.813129e+06,1.000000,21.800000,0.105300,0.130400,0.074000,0.195700,0.066120,1.474000,45.190000,...,0.023480,0.004558,29.720000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,9.113205e+08,1.000000,39.280000,0.163400,0.345400,0.201200,0.304000,0.097440,4.885000,542.200000,...,0.078950,0.029840,49.540000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

### Check Duplicate and Missing Value

In [6]:
duplicates = df.duplicated().sum()
duplicates

np.int64(0)

In [7]:
df.isna().sum()

id                         0
diagnosis                  0
texture_mean               0
smoothness_mean            0
compactness_mean           0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
texture_se                 0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
texture_worst              0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

### Feature Scaling

In [8]:
X = df.drop(columns=['id', 'diagnosis'])
y = df['diagnosis']

print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")

Features shape: (569, 22)
Target shape: (569,)

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns, index=X.index)
X_scaled

,texture_mean,smoothness_mean,compactness_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,texture_se,area_se,smoothness_se,compactness_se,...,symmetry_se,fractal_dimension_se,texture_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,-2.073335,1.568466,3.283515,2.532475,2.217515,2.255747,-0.565265,2.487578,-0.214002,1.316862,...,1.148757,0.907083,-1.359293,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,-0.353632,-0.826962,-0.487072,0.548144,0.001392,-0.868652,-0.876244,0.742402,-0.605351,-0.692926,...,-0.805450,-0.099444,-0.369203,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,0.456187,0.942210,1.052926,2.037231,0.939685,-0.398008,-0.780083,1.181336,-0.297005,0.814974,...,0.237036,0.293559,-0.023974,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,0.253732,3.283553,3.402909,1.451707,2.867383,4.910919,-0.110409,-0.288378,0.689702,2.744280,...,4.732680,2.047511,0.133984,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,-1.151816,0.280372,0.539340,1.428493,-0.009560,-0.562450,-0.790244,1.190357,1.483067,-0.048520,...,-0.361092,0.499328,-1.466770,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.721473,1.041842,0.219060,2.320965,-0.312589,-0.931027,0.071025,2.604187,1.086384,0.191805,...,-1.138416,0.167980,0.117700,2.015301,0.378365,-0.273318,0.664512,1.629151,-1.360158,-0.709091
565,2.085134,0.102458,-0.017833,1.263669,-0.217664,-1.058611,2.260938,1.291565,-0.424010,-0.069758,...,-0.189161,-0.490556,2.047399,1.494959,-0.691230,-0.394820,0.236573,0.733827,-0.531855,-0.973978
566,2.045574,-0.840484,-0.038680,0.105777,-0.809117,-0.895587,-0.257371,0.180698,-0.379342,0.661277,...,-0.891416,0.036727,1.374854,0.427906,-0.809587,0.350735,0.326767,0.414069,-1.104549,-0.318409
567,2.336457,1.525767,3.272144,2.658866,2.137194,1.043695,0.686088,1.009503,-0.173000,2.017716,...,0.326634,0.904057,2.237926,1.653171,1.430427,3.904848,3.197605,2.289985,1.919083,2.219635
568,1.221792,-3.112085,-1.150752,-1.261820,-0.820070,-0.561032,0.383092,-0.466152,0.049342,-1.163516,...,0.752830,-0.382754,0.764190,-1.075813,-1.859019,-1.207552,-1.305831,-1.745063,-0.048138,-0.751207

In [10]:
df_final = pd.concat([X_scaled, y], axis=1)
df_final

,texture_mean,smoothness_mean,compactness_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,texture_se,area_se,smoothness_se,compactness_se,...,fractal_dimension_se,texture_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis
0,-2.073335,1.568466,3.283515,2.532475,2.217515,2.255747,-0.565265,2.487578,-0.214002,1.316862,...,0.907083,-1.359293,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015,1
1,-0.353632,-0.826962,-0.487072,0.548144,0.001392,-0.868652,-0.876244,0.742402,-0.605351,-0.692926,...,-0.099444,-0.369203,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190,1
2,0.456187,0.942210,1.052926,2.037231,0.939685,-0.398008,-0.780083,1.181336,-0.297005,0.814974,...,0.293559,-0.023974,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391,1
3,0.253732,3.283553,3.402909,1.451707,2.867383,4.910919,-0.110409,-0.288378,0.689702,2.744280,...,2.047511,0.133984,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010,1
4,-1.151816,0.280372,0.539340,1.428493,-0.009560,-0.562450,-0.790244,1.190357,1.483067,-0.048520,...,0.499328,-1.466770,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.721473,1.041842,0.219060,2.320965,-0.312589,-0.931027,0.071025,2.604187,1.086384,0.191805,...,0.167980,0.117700,2.015301,0.378365,-0.273318,0.664512,1.629151,-1.360158,-0.709091,1
565,2.085134,0.102458,-0.017833,1.263669,-0.217664,-1.058611,2.260938,1.291565,-0.424010,-0.069758,...,-0.490556,2.047399,1.494959,-0.691230,-0.394820,0.236573,0.733827,-0.531855,-0.973978,1
566,2.045574,-0.840484,-0.038680,0.105777,-0.809117,-0.895587,-0.257371,0.180698,-0.379342,0.661277,...,0.036727,1.374854,0.427906,-0.809587,0.350735,0.326767,0.414069,-1.104549,-0.318409,1
567,2.336457,1.525767,3.272144,2.658866,2.137194,1.043695,0.686088,1.009503,-0.173000,2.017716,...,0.904057,2.237926,1.653171,1.430427,3.904848,3.197605,2.289985,1.919083,2.219635,1
568,1.221792,-3.112085,-1.150752,-1.261820,-0.820070,-0.561032,0.383092,-0.466152,0.049342,-1.163516,...,-0.382754,0.764190,-1.075813,-1.859019,-1.207552,-1.305831,-1.745063,-0.048138,-0.751207,0

### Export Dataset and Scaler

In [11]:
df_final.to_csv("D:\\Ameng\\Data Science Project\\breast-cancer-prediciton\\data\\processed\\final_scaled.csv", index=False)

In [12]:
joblib.dump(scaler, "D:\\Ameng\\Data Science Project\\breast-cancer-prediciton\\models\\scaler.pkl")

['D:\\Ameng\\Data Science Project\\breast-cancer-prediciton\\models\\scaler.pkl']